"""
Django settings for Murphy_Threads_Backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("under_development")

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'users',
    # 'cart',
    # 'extra',
    # 'orders',
    # 'product',
    # 'payments',
    # 'wishlist',
    'rest_framework_simplejwt',
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if config("under_development") == True:
    MIDDLEWARE.append("Murphy_Threads_Backend.middleware.ApiKeyMiddleware")

ROOT_URLCONF = "Murphy_Threads_Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Murphy_Threads_Backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config("db_engine"),
        'NAME': config("name"),
        'USER': config("user"),
        'PASSWORD': config("password"),
        'HOST': config("host"),
        'PORT': config("port"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
}

# if DEBUG == False:
#     REST_FRAMEWORK.update(
#         {
#             'DEFAULT_RENDERER_CLASSES': 'rest_framework.renderers.JSONRenderer'
#         }
#     )


EMAIL_BACKEND = config("email_backend")
EMAIL_HOST = config("email_host")
EMAIL_USE_TLS = config("email_use_tls")
EMAIL_PORT = config("email_port")
EMAIL_HOST_USER = config("email_host_user")
EMAIL_HOST_PASSWORD = config("email_host_password")

# STRIPE
STRIPE_PUBLISHABLE_LIVE_KEY = config("stripe_api_publishable_key_live")
STRIPE_SECRET_LIVE_KEY = config("stripe_api_secret_key_live")
STRIPE_PUBLISHABLE_TEST_KEY = config("stripe_api_publishable_key_test")
STRIPE_SECRET_TEST_KEY = config("stripe_api_secret_key_test")

# INSTAMOJO
INSTAMOJO_PRIVATE_LIVE_API_KEY = config("instamojo_private_live_api_key")
INSTAMOJO_PRIVATE_LIVE_AUTH_TOKEN = config("instamojo_private_live_auth_token")
INSTAMOJO_PRIVATE_LIVE_SALT = config("instamojo_private_live_salt")
INSTAMOJO_PRIVATE_TEST_API_KEY = config("instamojo_private_test_api_key")
INSTAMOJO_PRIVATE_TEST_AUTH_TOKEN = config("instamojo_private_test_auth_token")
INSTAMOJO_PRIVATE_TEST_SALT = config("instamojo_private_test_salt")

# PAYPAL
PAYPLA_TEST_CLIENT_ID = config("paypal_sandbox_client_id")
PAYPLA_TEST_SECRET_KEY = config("paypal_sandbox_secret_key")
PAYPLA_LIVE_CLIENT_ID = config("paypal_live_client_id")
PAYPLA_LIVE_SECRET_KEY = config("paypal_live_secret_key")

IS_UNDER_DEVELOPMENT = config("under_development")

API_KEY = config("api_key")

AUTH_USER_MODEL = 'users.Users'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
}

# set this to forntend hosts
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

#IT TAKES VALUES IN SECONDS, 900 SECONDS MEANS 15 MINUTES
PASSWORD_RESET_TIMEOUT = 900 