from django.shortcuts import render

# Create your views here.

def get_user_by_username(request):
    ...
def get_user_by_id(request):
    ...
def get_user_addresses(request):
    ...
def create_new_user(request):
    ...
def update_user(request):
    ...
def delete_user(request):
    ...
def activate_account(request):
    ...
def request_password_reset(request):
    ...
def reset_pass(request):
    ...
def add_new_address(request):
    ...
def update_address(request):
    ...
def delete_address(request):
    ...