# Generated by Django 4.2.15 on 2024-08-29 04:40

import Utils.AutoField
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    Utils.AutoField.CustomAutoField(
                        max_length=255,
                        prefix="user_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("phone_no", models.CharField(max_length=13)),
                (
                    "country_code",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAddresses",
            fields=[
                (
                    "id",
                    Utils.AutoField.CustomAutoField(
                        max_length=255,
                        prefix="addr_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("address_line_1", models.CharField(max_length=800)),
                ("address_line_2", models.CharField(max_length=800, null=True)),
                ("house_no", models.CharField(max_length=800, null=True)),
                ("street", models.CharField(max_length=800, null=True)),
                ("landmark", models.CharField(max_length=800, null=True)),
                ("city", models.CharField(max_length=800, null=True)),
                ("state", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("phone_no_1", models.CharField(max_length=255)),
                ("phone_no_2", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
