# Generated by Django 5.2 on 2026-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
