shiprocket_couriers = {
    1: "Blue Dart",
    6: "DTDC Surface",
    10: "Delhivery",
    14: "Ecom Express Surface",
    33: "Xpressbees",
    35: "Aramex International",
    43: "Delhivery Surface",
    45: "Ecom Express Reverse",
    46: "Shadowfax Reverse",
    48: "Ekart Logistics",
    51: "Xpressbees Surface",
    54: "Ekart Logistics Surface",
    55: "Blue Dart Surface",
    58: "Shadowfax Surface",
    60: "Ecom Premium and ROS",
    61: "Delhivery Reverse",
    64: "Delhivery 500G Savex (A)",
    65: "Delhivery 500G Savex (S)",
    66: "Ecom Exp Savex (A)",
    67: "Ecom ROS Savex (A)",
    69: "Kerry Indev Express Surface",
    71: "Self Delivery",
    72: "Bluedart Savex (A)",
    75: "SRF Standard 500gm",
    81: "SRF Standard",
    85: "Standard",
    86: "Express",
    90: "Standard 500gm",
    95: "Shadowfax Local",
    97: "Dunzo Local",
    99: "Ecom Express ROS Reverse",
    106: "Borzo",
    115: "Shadowfax Savex",
    117: "SRF Express",
    118: "Bluedart Savex Exchange",
    119: "Identify Plus SDD Lite",
    120: "Identify Plus SDD Standard",
    125: "Xpressbees Reverse",
    126: "Bluedart Savex TDD",
    140: "SRX Premium",
    141: "SRF RUSH",
    142: "Amazon Surface 500gm Prepaid",
    154: "Kerry Indev Express",
    195: "Amazon Surface 500gm COD",
    196: "DTDC 500GMS",
    235: "DTDC Express",
    240: "SRX Priority",
    313: "Wholemark",
    501: "Bluedart CE Savex",
    777: "Shadowfax DS",
}

shipment_statuses = {
    1: "AWB Assigned",
    2: "Label Generated",
    3: "Pickup Scheduled/Generated",
    4: "Pickup Queued",
    5: "Manifest Generated",
    6: "Shipped",
    7: "Delivered",
    8: "Cancelled",
    9: "RTO",
    10: "RTO Delivered",
    14: "RTO Acknowledged",
    19: "Out For Pickup",
    40: "RTO NDR",
    41: "RTO OFD",
    46: "RTO_IN_TRANSIT",
    20: "Pickup Exception",
    24: "Destroyed",
    26: "Fulfilled",
    38: "Reached at Destination",
    23: "Partial_Delivered",
    43: "Self Fulfilled",
    44: "DISPOSED_OFF",
    45: "CANCELLED_BEFORE_DISPATCHED",
    47: "QC Failed",
    48: "Reached Warehouse",
    49: "Custom Cleared",
    50: "In Flight",
    51: "Handover to Courier",
    52: "Shipment Booked",
    54: "In Transit Overseas",
    55: "Connection Aligned",
    56: "Reached Overseas Warehouse",
    57: "Custom Cleared Overseas",
    59: "Box Packing",
}


tracking_shipment_statuses = {
    6: "Shipped",
    7: "Delivered",
    8: "Cancelled",
    9: "RTO Initiated",
    10: "RTO Delivered",
    12: "Lost",
    13: "Pickup Error",
    14: "RTO Acknowledged",
    15: "Pickup Rescheduled",
    16: "Cancellation Requested",
    17: "Out For Delivery",
    18: "In Transit",
    19: "Out For Pickup",
    20: "Pickup Exception",
    21: "Undelivered",
    22: "Delayed",
    23: "Partial Delivered",
    24: "DESTROYED",
    25: "DAMAGED",
    26: "FULFILLED",
    27: "Pickup Booked",
    38: "REACHED AT DESTINATION HUB",
    39: "MISROUTED",
    40: "RTO_NDR",
    41: "RTO_OFD",
    42: "PICKED UP",
    43: "SELF FULFILLED",
    44: "DISPOSED OFF",
    45: "CANCELLED_BEFORE_DISPATCHED",
    46: "RTO IN INTRANSIT",
    47: "QC FAILED",
    48: "Reached Warehouse",
    49: "Custom Cleared",
    50: "In Flight",
    51: "Handover to Courier",
    52: "Shipment Booked",
    54: "In Transit Overseas",
    55: "Connection Aligned",
    56: "Reached Overseas Warehouse",
    57: "Custom Cleared Overseas",
    59: "Box Packing",
    68: "PROCESSED AT WAREHOUSE",
    60: "FC Allocated",
    61: "Picklist Generated",
    62: "Ready To Pack",
    63: "Packed",
    67: "FC MANIFEST GENERATED",
    71: "HANDOVER EXCEPTION",
    72: "PACKED EXCEPTION",
}
