from instamojo_wrapper import Instamojo
from django.conf import settings

instamojo_api = Instamojo(api_key=settings.INSTAMOJO_PRIVATE_LIVE_API_KEY,auth_token=settings.INSTAMOJO_PRIVATE_LIVE_AUTH_TOKEN)